### ISSUE TITLE
Tor not found troubleshooting

### ISSUE THREAD

**Issue by NiKola-UE** [DcodingTheWeb/ProxAllium#18] opened 2024-06-04 15:23 UTC
I think the update is necessary because connecting to Tor with the latest version released so far doesn't seem to be possible anymore and I keep getting the unavailability error even though I've done everything right. 

Thank you.

**Comment by TheDcoder** [comment] 2024-06-04 15:34
Thanks for reporting the issue, I'll take a look and fix it as soon as possible :)

**Comment by NiKola-UE** [comment] 2024-06-04 23:06
That's great and I'm glad about it! 

Apart from the problem with connecting to Tor, there are no other errors. The tool works great even without Tor Browser, and antiviruses don't report anything suspicious anymore, which happened most often back when ProxAllium was on SourceForge, when even VirusTotal rated it as harmful. But now that's gone. 




However, try adding an auto-update option or some similar, so that every new version doesn't have to be checked and downloaded manually ewery time. 






Another side question: Can the OnionCat's source code be used for any improved performance or something?

**Comment by TheDcoder** [comment] 2024-06-05 00:34
> which happened most often back when ProxAllium was on SourceForge, when even VirusTotal rated it as harmful. But now that's gone.

I'm glad to hear about the reduction in false positives but ProxAllium was never on SourceForge, I never put it there.

> try adding an auto-update option or some similar

I have pretty much stopped development on this version of ProxAllium, I have plans for a cross-platform rewrite in Rust but there is no timeline for it.

In the meanwhile you can subscribe to notifications for releases via [RSS](https://github.com/DcodingTheWeb/ProxAllium/releases.atom) or by watching this repository, in which case GitHub would send you an email upon a new release.

> Can the OnionCat's source code be used for any improved performance or something?

No, ProxAllium is just a nice GUI for Tor's command-line interface so any performance improvements or such would only come from Tor.

**Comment by TheDcoder** [comment] 2024-06-05 01:46
> I think the update is necessary because connecting to Tor with the latest version released so far doesn't seem to be possible anymore and I keep getting the unavailability error even though I've done everything right.

@NiKola-UE I just the latest version of Tor from the Tor browser, it's still functioning, the only issue I noticed was an error connecting to Tor's control interface but that's not a critical issue, Tor should still function fully.

Can you give me the exact error message and the version of Tor that you are using? Are you using bridges? If so, can you try disabling them to see if that fixes the issue?

**Comment by NiKola-UE** [comment] 2024-06-05 15:55
Yes, you're right, ProxAllium was never really on the SourceForge. It was a another Tor-based proxy tool with a similar name that was out there that was really full of viruses - sorry for the mistake. 





As for 
[OnionCat, ](https://github.com/rahra/onioncat), 
it's a very interesting tool that makes Tor Browser even more experimental, so I thought it could be complementary, but well... 



I don't remember exactly which version of the Tor Browser I downloaded because it's been updated several times in the meantime, but the current one is 13.0.13, which I think is the latest. Otherwise, I don't have any problems with the Tor Browser, although sometimes it takes a while to connect. Of the bridges, I only use Snowflake, and I also have 
[OnionFruit Connect](https://dragonfruit.network/) 
installed, so I don't know if that's a problem. 




As for ProxAllium, when I open it, it says this:

> "Starting Tor... Invalid Tor configuration, please check your custom entries." 

So, ProxAllium's Control Panel also not works, ie. can't start. When I open the menu by pressing Alt key, the first "ProxAllium" menu is unavailable in the sense that the options from it cannot be seen. It is interesting that I downloaded and tried to use it before Tor Browser, but the same error was repeated. 








In any case, I am convinced that the cross-platform program on which the raid is currently running will be even better, more efficient and more resistant.

**Comment by TheDcoder** [comment] 2024-06-06 20:32
> As for ProxAllium, when I open it, it says this:
> >    "Starting Tor... Invalid Tor configuration, please check your custom entries."

Do you have any custom entries in your Tor configuration? If not, try regenerating your config via the `Options` -> `Regenerate Tor configuration` menu option.

> When I open the menu by pressing Alt key, the first "ProxAllium" menu is unavailable in the sense that the options from it cannot be seen.

It is actually meant to be that way, it is always disabled and doesn't actually do anything even if you hack it to enable it :)

It's purely for cosmetic purposes, in hindsight it may have been a bad idea... but back then I thought it was somewhat cool :P

> In any case, I am convinced that the cross-platform program on which the raid is currently running will be even better, more efficient and more resistant.

Thanks, I hope it will be!

**Comment by NiKola-UE** [comment] 2024-06-06 23:19
I didn't use the bridges. I've tried everything you told me, but the same thing keeps happening. I even run the Tor setup again, but still the same; all same as inmediately after first starting. But when I tried to click to "New Tor circuit for future connections", I got an error"Line 13387 file" (I don't remember exactly what it said, but it mentions "Error: a ray Wariable has incorrect subscript or superscript dimension range exceeded", so you probably know what it actually refers to). The only thing that comes to mind is the location (in my case, it is "C:\Users\username\AppData\Local\Programs\" - the same is for Tor Browser and ProxAllium) because I don't like to store these kinds of tools right on the desktop, although I don't know if that could have any effect. 







However, when that new program turns out to be even better, ProxAllium may no longer be necessary. Fortunately, there are more and more FOSS decentralized P2P and E2E networks, tools  and protocols for privacy and anonymity. I don't know anything about programming, although I'm trying to learn, but I often visit the site AlternativeTo.net where I first time heard for ProxAllium and many more. 










Greeting.

**Comment by TheDcoder** [comment] 2024-06-09 02:04
> But when I tried to click to "New Tor circuit for future connections", I got an error"Line 13387 file" (I don't remember exactly what it said, but it mentions "Error: a ray Wariable has incorrect subscript or superscript dimension range exceeded", so you probably know what it actually refers to).

Seems like you caught a bug in the code, unfortunately the line number from the compiled code is almost useless.

I don't really see any reason why it shouldn't work. We can try resetting everything and see if it still doesn't work, can you extract a fresh copy of ProxAllium into a different folder and try it?

**Comment by NiKola-UE** [comment] 2024-07-10 22:26
I apologize for being late to reply. I tried but nothing helps. 







As you said, you are already working on a new project. I don't know what kind of project it is yet, but if it's something that's also related to security and privacy, then I can try that too, which I'm happy to do. Of course, you can stop the development of ProxAlium if you judge that there is no longer a need for it, and we can close this issue.

**Comment by TheDcoder** [comment] 2024-07-12 08:25
> I apologize for being late to reply. I tried but nothing helps.

No worries, luckily we can figure out the correct source of the error by running the code without compiling it :)

You'll have to install AutoIt (the language which the current ProxAllium is written in) on your PC, get it from the official website: https://www.autoitscript.com/site/autoit/downloads/ (Get the "AutoIt Full Installation" setup file)

After you install it download the [source code](https://github.com/DcodingTheWeb/ProxAllium/archive/refs/tags/v0.4.3.zip) of ProxAllium and extract it in a folder, now right click on `ProxAllium.au3` and choose the "Run script" option to run the program :)

Send me a screenshot of the error after doing that, it should contain the exact line where the error occurs at.

**Comment by NiKola-UE** [comment] 2024-07-12 20:23
Uh, I'm not sure if I'll be able to report all this successfully and how much because I don't know anything about programming and programming languages, but I'll be happy to learn something new because it's a challenge for me and I'm more and more interested in these things. I'm just asking you to have a little patience because I can't do everything right now.

**Comment by TheDcoder** [comment] 2024-07-12 21:34
Take your time, no hurry!

You don't really need to know any porgramming to do this, just follow my instructions and you should be able to get it runnning from the source code!

Let me know if you have any questions or issues.

**Comment by NiKola-UE** [comment] 2024-07-12 22:52
OK, thank you.

**Comment by NiKola-UE** [comment] 2024-07-15 23:49
I did everything as you said, but it's still the same. The same error appears at the beginning and when I click on the "Start Control panel" nothing happens and also  the same with the other options mentioned. It seems that I didn't manage to take a screenshots because after I pressing the Shift +Print Screen keys nothing happened since I can't find those pictures anywhere.

**Comment by TheDcoder** [comment] 2024-07-16 04:32
Windiws has a dedicated screenshot tool that you can use: https://my.wlu.edu/its/how-to/snipping-tool-for-windows

**Comment by NiKola-UE** [comment] 2024-07-16 14:10
I don't have a problem with the screenshots, but I note that as a blind computer user who uses screen readers, I can't tell if I did it right.

**Comment by TheDcoder** [comment] 2024-07-17 06:11
Ah! I wasn't aware that you were blind. No worries though :)

Are you able to detect when the error pops up? If so, you can just take a full screen screenshot and send it here.

If you're concerned about the privacy of your desktop you can also mail the image to me personally at TheDcoder@protonmail.com

**Comment by NiKola-UE** [comment] 2024-07-17 15:11
In particular, when ProxAllium is opened, the field that shows the Tor status simply says the following: 


> "Starting ProxAllium... Please wait :) 
> Detected Tor version: 0.4.8.10 (git-680415826c5fd786) 
> Starting Tor... Invalid Tor configuration, please check your custom entries." 




Before this, it says that Tor PID is not running, there are only three dots in the Control panel status field, also button for start of control panel not works, and it also mentions some error stating the location of Tor, but I don't remember what was the problem. I think all the problems come from this, which is why I assumed it needed an update because most apps or tools that use Tor and haven't been updated for a while have connection problems. But it is possible that the problem is something else. If you think it's still necessary, I'll send a screenshot here, but I can't guarantee that everything will be painted correctly, although screen readers nowadays can pretty much read image descriptions with the help of artificial intelligence, and there are specialized programs for that.

**Comment by TheDcoder** [comment] 2024-07-22 05:08
Can you send the `torrc` file? I'll check why it's invalid.

**Comment by NiKola-UE** [comment] 2024-07-22 15:50
Do you mean the "torrc" file from Tor Browser or...?

**Comment by TheDcoder** [comment] 2024-07-23 08:35
I meant the `torrc` file in ProxAllium's folder, we don't use any configuration from the Tor Browser.

The only relation between ProxAllium and the Tor Browser is that ProxAllium optionally uses the core Tor executable from the browser :smile:

**Comment by NiKola-UE** [comment] 2024-07-23 18:00
Yes, I understand now. As far as I know, ProxAllium can work well without Tor Browser, but we are not talking about that here. 
 



They mean  "config.torrc" file which is exactly the same into the both "ProxAllium" folder and source code. Here's what it says there (of course without quotes): 


> "## Configuration file automatically generated by ProxAllium
> ## This file was generated on 16/07/2024 01:39:25 AM
> 
> ## Open SOCKS proxy on the following port
> SOCKSPort 9050
> 
> ## Open the Tor controller interface on the following port
> ControlPort 9051
> HashedControlPassword 16:A5BD28C31D1D7D7A600A46DA4AA0FA0964CCD43CA5B19CF060EE96A109
> 
> ## Only accept connections from localhost
> SOCKSPolicy accept 127.0.0.1
> SOCKSPolicy accept6 [::1]
> SOCKSPolicy reject *
> 
> ## GeoIP Files
> GeoIPFile Tor\geoip
> GeoIPv6File Tor\geoip6
> 
> ## Data Directory
> DataDirectory Tor Data
> 
> ## Bridges
> UseBridges 1
> ClientTransportPlugin snowflake exec C:\Users\username\AppData\Local\Programs\Tor Browser\Browser\TorBrowser\Tor\PluggableTransports\snowflake-client.exe -url=https://snowflake-broker.torproject.net.global.prod.fastly.net/ -front=cdn.sstatic.net -ice=stun:stun.voip.blackberry.com:3478,stun:stun.altar.com.pl:3478,stun:stun.antisip.com:3478,stun:stun.bluesip.net:3478,stun:stun.dus.net:3478,stun:stun.epygi.com:3478,stun:stun.sonetel.com:3478,stun:stun.sonetel.net:3478,stun:stun.stunprotocol.org:3478,stun:stun.uls.co.za:3478,stun:stun.voipgate.com:3478,stun:stun.voys.nl:3478
> 
> ###########################################################
> ###### STORE YOUR CUSTOM CONFIGURATION ENTRIES BELOW ######
> ##### THEY WILL BE PRESERVED ACROSS CHANGES IN CONFIG #####
> ###########################################################
> #~ I (this line) am used to identify the start of custom entries, so please do not touch me :)" 












I don't think the problem is the location of the Tor Browser because it works there without any errors, and I don't know why Blackberry is mentioned because I don't use it and never have. I find this "Please do not touch me" interesting, but I don't know what it's supposed to mean.

**Comment by TheDcoder** [comment] 2024-07-23 18:09
Ah, looks like you have bridges enabled, those can be the source of the issue. Can you delete the `config.ini` and `torrc` files in ProxAllium's folder?

Let me know if you still get the error after deleting those files.

> and I don't know why Blackberry is mentioned because I don't use it and never have.

It's part of the default configuration for the Snowflake bridge, the configuration is very outdated at this point, I should remove it...

Blackberry ceased to exist a couple of years ago so that server should be dead.

> I find this "Please do not touch me" interesting, but I don't know what it's supposed to mean.

It's just to warn users in case they want to edit the `torrc` file manually to add their own changes, they should only added their changes after that line because everything before it is automatically generated by ProxAllium :smile:

**Comment by NiKola-UE** [comment] 2024-07-23 21:26
I admit I don't remember exactly what it said now, but after I deleted all config. files from both ProxAllium and code, the first time I started ProxAllium, it said something like: "ProxAllium can't start properly. Don't worry, ProxAllium works." Then app asked me again if I had a Tor Browser, and when I answered in the affirmative, the same error appeared again, but now it also said: "Unable to find Tor!" And about somewhere near the end again: "Can't find Tor! Success!" After the second run it didn't mention if it could find Tor, but everything else remained the same as before. I only use Snowflake in the Tor Browser and other browsers, while in ProxAllium I don't use any bridges that I don't think works for me anyway.

**Comment by TheDcoder** [comment] 2024-07-25 07:46
That's the setup wizard (just a series of interactive messages) that pops up when there is no configuration to help new users set up Tor.

ProxAllium used to ship with Tor in the past but not anymore, I suspect that you might've been using ProxAllium since that time, am I right?

In any case, you'll have to properly go through the setup wizard, which involves selecting the location of the Tor browser after answering affirmative. Are you able to complete this as a visually-impaired user? The dialog box that opens to select the location is a standard Windows folder picker dialog, in this dialog you must select the location of the "Tor Browser" folder that you chose while installing the Tor Browser.

You can run the setup wizard again by using the menu options in ProxAllium or by deleting the config files again.

So give it a go and let me know if that works.

**Comment by NiKola-UE** [comment] 2024-07-25 11:44
Yes, I've done all this many times before. As you can see, I'm good at computers. After it finds the location of Tor Browser, those errors that we have already talked about appear. So it's nothing complicated. But why these errors occur, I still don't know.

**Comment by TheDcoder** [comment] 2024-07-25 18:03
Good to know! Are you still getting the same "Cannot find Tor" error?

If so, can you paste the contents of `config.ini` here?

**Comment by NiKola-UE** [comment] 2024-07-26 15:57
Yes, the same errors are repeated over and over again. I currently can't copy the of the "config.ini" file right now because they didn't come back after the restore. The only thing is to download and take over everything again.

**Comment by TheDcoder** [comment] 2024-07-26 21:31
`config.ini` is automatically generated on launch if it doesn't exist, so can you check for it again? It should be in the same folder as `ProxAllium.exe`.

**Comment by NiKola-UE** [comment] 2024-07-31 15:45
I'm late in replying again, but I've been busy. 







Of course I know which files you mean, but I had deleted everything with the name "Config", so I had to download everything again, but the problems are the same again. The file "Config.ini" is identical to the "Config.torrc" - and there are mentions of bridges, Snowflake and Blackberry which was shut down almost seven years ago. Here's what it says there (I'm quoting without quotation marks): 









[tor]
path=C:\Users\username\AppData\Local\Programs\Tor Browser\Browser\TorBrowser\Tor\tor.exe
obfs4_path=Tor\PluggableTransports\obfs4\obfs4proxy.exe
snowflake_path=C:\Users\username\AppData\Local\Programs\Tor Browser\Browser\TorBrowser\Tor\PluggableTransports\snowflake-client.exe
snowflake_args=-url=https://snowflake-broker.torproject.net.global.prod.fastly.net/ -front=cdn.sstatic.net -ice=stun:stun.voip.blackberry.com:3478,stun:stun.altar.com.pl:3478,stun:stun.antisip.com:3478,stun:stun.bluesip.net:3478,stun:stun.dus.net:3478,stun:stun.epygi.com:3478,stun:stun.sonetel.com:3478,stun:stun.sonetel.net:3478,stun:stun.stunprotocol.org:3478,stun:stun.uls.co.za:3478,stun:stun.voipgate.com:3478,stun:stun.voys.nl:3478
config_file=config.torrc
data_dir=Tor Data
geoip4_file=Tor\geoip
geoip6_file=Tor\geoip6
[proxallium]
output_poll_interval=100
[tor_config]
port=9050
control_port=9051
control_pass=562688
localhost_only=true

**Comment by TheDcoder** [comment] 2024-08-02 00:02
According to your config file `tor.exe` should be located at `C:\Users\username\AppData\Local\Programs\Tor Browser\Browser\TorBrowser\Tor\tor.exe`, can you manually check that location in File Explorer to see if it really exists?

> there are mentions of bridges, Snowflake and Blackberry which was shut down almost seven years ago.

There's no need to worry about that, it's just part of the default configuration, it shouldn't have any effect on you unless you use the Snowflake bridge (which you are not).

**Comment by NiKola-UE** [comment] 2024-08-02 20:32
Yes, Tor Browser is really there for me, and ProxAllium is also in the "Programs" folder because I set everything up manually. I also moved ProxAllium to the Desktop, but nothing helps. Do you think the problem may lie in the location?

**Comment by TheDcoder** [comment] 2024-08-05 13:47
> Do you think the problem may lie in the location?

Yes, the "Cannot find Tor" only occurs when ProxAllium cannot find the `tor.exe` file, so it's quite puzzling if it does exist at that location.

By the way, are you using any translation service to translate your messages to English?

**Comment by NiKola-UE** [comment] 2024-08-05 17:50
In other words, both Tor Browser and ProxAllium must be exclusively on the desktop, right? 








I rely on automatic translators occasionally because my vocabulary is very limited.

**Comment by TheDcoder** [comment] 2024-08-05 18:02
The location shouldn't matter as long as the files are accessible at the configured, I am not sure why it's not working in your PC.

What is your native language by the way?

Also I'm closing the issue as this does not look like a bug in ProxAllium.

**Comment by NiKola-UE** [comment] 2024-08-05 21:20
My native language is Serbian, or Serbo-Croatian, whatever you want (the differences are more political than linguistic). I understand English well when I read, but I'm pretty bad at writing due to the lack of interaction, social isolation, to which blindness and deafness further contributed. 




I have no problems with Tor Browser because it works flawlessly. Again, maybe the proxAllium is missing some more fundamental updates, but I could be wrong. 




Feel free to close this issue if you think it's best, but before that just tell me a little more about that new project you're working on because I'm very interested in trying it out and what it's all about. Thank you.

**Comment by TheDcoder** [comment] 2024-08-06 23:42
> I understand English well when I read, but I'm pretty bad at writing due to the lack of interaction, social isolation, to which blindness and deafness further contributed.

I'm sorry to hear that, but it's nothing a bit of practice can't fix! I suggest finding places where you can chat with others, it can be very good practice for English :)

> I have no problems with Tor Browser because it works flawlessly. Again, maybe the proxAllium is missing some more fundamental updates, but I could be wrong.

I'm totally lost on what the problem is... so I can't really help you out without having complete access to your PC like I'm using it :sweat_smile:

Perhaps you can think of possible causes and investigate the issue yourself, think about what changed when ProxAllium stopped working for you.

> Feel free to close this issue if you think it's best, but before that just tell me a little more about that new project you're working on because I'm very interested in trying it out and what it's all about. Thank you.

The new project hasn't even begun yet, the plan is to deliver the same ProxAllium experiences in other OSes as well, particularly Linux because that's what I've been using for many years now, when I was actively developing ProxAllium I was using Windows so that's why it's Windows-only for now.

Aside from that I have a few other ideas but we'll have to see if I can get to that stage :)

**Closed as completed by TheDcoder** 2024-08-06 23:42 UTC
Labels: question
